name: Release Flutter APK

on:
  workflow_call:

jobs:
  release-flutter:
    name: Release Flutter APK to GitHub
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: test_flutter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: test_flutter/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK to GitHub Release (latest)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: test_flutter/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
