name: Main Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backend-build:
    uses: ./.github/workflows/backend-build.yml@main

  backend-push:
    needs: backend-build
    uses: ./.github/workflows/backend-push.yml@main

  flutter-build:
    uses: ./.github/workflows/flutter-build.yml@main

  flutter-release:
    needs: flutter-build
    uses: ./.github/workflows/flutter-release.yml@main
