name: Main Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  backend-build:
    uses: ./.github/workflows/backend-build.yml

  backend-push:
    needs: backend-build
    uses: ./.github/workflows/backend-push.yml
    permissions:
      packages: write
      id-token: write

  flutter-build:
    uses: ./.github/workflows/flutter-build.yml

  flutter-release:
    needs: flutter-build
    uses: ./.github/workflows/flutter-release.yml
    permissions:
      contents: write
